### ISSUE TITLE
Overlap between taps panel and tabs when the sidebar is minimized. Sidebery beta V5.

### ISSUE THREAD

**Issue by JacoboGuijar** [mgastonportillo/gale-for-ff#1]
I am using sidebery V5 beta. When the sidebar is minimized the taps panel and tabs overlap.
This are the tabs expanded when the mouse hovers over them:

![image](https://github.com/mgastonportillo/gale-for-ff/assets/56597297/29c00bc6-e2a2-49f3-9c10-f25835bcaccd)

And this is the look when the sidebar is minimized:

![image](https://github.com/mgastonportillo/gale-for-ff/assets/56597297/1372f059-c1d8-42be-b729-4995f0ebf6f6)

Is there any way to avoid this overlapping? Thanks for your time.

**Comment by mgastonportillo** [comment]
@JacoboGuijar I checked it with the latest Sidebery beta (it's specified in the new file) and was able to modify mostly everything I wanted to. If you are willing to check it out, re-download the userChrome.css file for your OS (version mostly for aesthetic reasons and because I'm on Linux right now).

**Comment by mgastonportillo** [comment]
Closed as I implemented support for Sidebery v5 beta.
