### ISSUE TITLE
Where's the icons-only css?

### ISSUE THREAD

**Issue by devxan** [mgastonportillo/gale-for-ff#3]
I loved the collapsing function of this userchrome. Where'd that go?
Specifically pieces like `--uc-autohide-sidebar-delay`

**Comment by mgastonportillo** [comment]
Hey Xan, that version can be found inside of the [legacy](https://github.com/mgastonportillo/gale-for-ff/tree/main/legacy) folder

**Comment by devxan** [comment]
Why was that feature removed?

**Comment by mgastonportillo** [comment]
I decided to support Sidebery v5 beta since it has significant upgrades in comparison to v4, but it has an incompatibility with dragging/moving tabs around and the auto-shrink feature. It was easier to deal with it by removing it than coordinating a workaround. I'll bring it back by default once it's fully compatible.

**Comment by devxan** [comment]
Awesome. Well then, I wanna say that I love the work you're doing and it makes Firefox (LibreWolf) my favorite browser experience *ever* ✨ by far!

**Comment by mgastonportillo** [comment]
That makes all the effort and time put into it, and making the decision to share it, well worth it. Thanks for your kind words!
